apiVersion: v1
kind: Service
metadata:
  labels:
    app: faker
  name: faker
  namespace: default
spec:
  ports:
  - port: 9000
    name: metrics
    protocol: TCP
    targetPort: 9000
  selector:
    app: faker
  type: ClusterIP