# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  main: main.go
  binary: konsumerator
  goos:
    - linux
  goarch:
    - amd64
archives:
- replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    binaries:
      - konsumerator
    dockerfile: Dockerfile-releaser
    image_templates:
      - "quay.io/lwolf/konsumerator:{{ .Tag }}"
      - "quay.io/lwolf/konsumerator:latest"
      - "docker.pkg.github.com/lwolf/konsumerator/{{ .Tag }}"
      - "docker.pkg.github.com/lwolf/konsumerator/latest"
