kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 9090
        hostPort: 30666
        protocol: tcp # Optional, defaults to tcp
