{
 "title": "Konsumerator overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "consumer",
    "query": "label_values(konsumerator_consumer_status, consumer)"
   }
  ]
 },
 "panels": [
  { "title": "Status ($consumer)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(konsumerator_consumer_status{consumer=~\"$consumer\"}) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Status update duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "konsumerator_consumer_status_update_duration_seconds{consumer=~\"$consumer\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Consumer $consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Reconcile events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(konsumerator_consumer_reconcile_total{consumer=~\"$consumer\"}[2m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(konsumerator_consumer_reconcile_errors_total{consumer=~\"$consumer\"}[2m]) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Reconcile duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "konsumerator_consumer_reconcile_duration_seconds{consumer=~\"$consumer\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Deployments create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(konsumerator_consumer_deployments_create_total{consumer=~\"$consumer\"}[2m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(konsumerator_consumer_deployments_create_errors{consumer=~\"$consumer\"}[2m]) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Deployments delete",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(konsumerator_consumer_deployments_delete_total{consumer=~\"$consumer\"}[2m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(konsumerator_consumer_deployments_delete_errors{consumer=~\"$consumer\"}[2m]) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Deployments update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(konsumerator_consumer_deployments_update_total{consumer=~\"$consumer\"}[2m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(konsumerator_consumer_deployments_update_errors{consumer=~\"$consumer\"}[2m]) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Deployments status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(konsumerator_deployment_status{consumer=~\"$consumer\"} == 0)",
     "legendFormat": "RUNNING"
    },
    {
     "expr": "count(konsumerator_deployment_status{consumer=~\"$consumer\"} == 1)",
     "legendFormat": "SATURATED"
    },
    {
     "expr": "count(konsumerator_deployment_status{consumer=~\"$consumer\"} == 2)",
     "legendFormat": "PENDING_SCALE_UP"
    },
    {
     "expr": "count(konsumerator_deployment_status{consumer=~\"$consumer\"} == 3)",
     "legendFormat": "PENDING_SCALE_DOWN"
    },
    {
     "expr": "count(konsumerator_deployment_status{consumer=~\"$consumer\"} == -1)",
     "legendFormat": "UNKNOWN"
    }
   ]
  },
  {
   "title": "Deployment CPU saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(konsumerator_deployment_saturation{consumer=~\"$consumer\"}) by(deployment) > 0 ) / 1e3",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Metrics Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Requests ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_prometheus_mp_requests_total{consumer=~\"$consumer\"}[2m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests duration 0.99 perc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(konsumerator_prometheus_mp_request_duration_seconds{consumer=~\"$consumer\", quantile=\"0.99\"}) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_prometheus_mp_requests_errors_total{consumer=~\"$consumer\"}[2m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Sub-requests ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_prometheus_mp_sub_requests_total{consumer=~\"$consumer\"}[2m])) by(addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Sub-requests duration 0.99 perc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(konsumerator_prometheus_mp_sub_request_duration_seconds{consumer=~\"$consumer\", quantile=\"0.99\"}) by(addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Sub-request errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_prometheus_mp_sub_requests_errors_total{consumer=~\"$consumer\"}[2m])) by(addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  }
 ]
}