{
 "title": "Konsumerator test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Production rate by partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_messages_production_offset[2m])) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Consumption rate by partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum(rate(konsumerator_messages_consumption_offset[2m])) by (partition)",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "CPU shares (requests) in millicores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "millicore" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\ncontainer_spec_cpu_shares{container=\"consumer\"},\n\"partition\",\n \"$1\",\n \"pod_name\",\n \"test-consumer-(.*)-(.*)-(.*)\"\n)) by (partition)",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "Lag in messages by partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "max(konsumerator_messages_production_offset) by (partition) - max(konsumerator_messages_consumption_offset) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Konsumerator API calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{client=~\"konsumerator.*\"}[2m]))"
    }
   ]
  }
 ]
}