name: tests

on:
  push:

jobs:
  ## Unit Tests
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
        id: go

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Download binaries
        # $(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        run: |
          mkdir -p /opt/bin
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /opt/bin/
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kube-apiserver && chmod +x kube-apiserver && mv kube-apiserver /opt/bin/
          bash hack/download_etcd.sh v3.3.13 /opt/bin
          echo 'KUBEBUILDER_ASSETS=/opt/bin' >> $GITHUB_ENV
      - name: Unit Test
        run: go test -race ./api/... ./controllers/... ./pkg/... -coverprofile=coverage.txt -covermode=atomic

      - name: Coverage
        if: github.repository == 'lwolf/konsumerator' # don't run on forks since secrets are not copied to forked repos
        env:
          CI_BRANCH: ${{ github.ref }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
